export const SET_WORKSPACE_FILE_DATA = 'SET_WORKSPACE_FILE_DATA';
export const SET_MY_FUNCTIONS_FILE_DATA = 'SET_MY_FUNCTIONS_FILE_DATA';
export const SET_MY_FUNCTIONS = 'SET_MY_FUNCTIONS';
export const OPEN_EXPORT_MODAL = 'OPEN_EXPORT_MODAL';
export const CLOSE_EXPORT_MODAL = 'CLOSE_EXPORT_MODAL';
export const OPEN_IMPORT_MODAL = 'OPEN_IMPORT_MODAL';
export const CLOSE_IMPORT_MODAL = 'CLOSE_IMPORT_MODAL';