export const UPDATE_BOARD = 'UPDATE_BOARD';
export const SET_EVAL_INSTRUCTION = 'SET_EVAL_INSTRUCTION';
export const SET_WORKSPACE_FUNCTION_BODY = 'SET_WORKSPACE_FUNCTION_BODY';
export const SET_RESULT_EVAL = 'SET_RESULT_EVAL';