export const UPDATE_BOARD = 'UPDATE_BOARD';
export const SET_EVAL_INSTRUCTION = 'SET_EVAL_INSTRUCTION';
export const SET_WORKSPACE_FUNCTION_BODY = 'SET_WORKSPACE_FUNCTION_BODY';
export const SET_RESULT_EVAL = 'SET_RESULT_EVAL';
export const SET_START_JOIN = 'SET_START_JOIN';
export const SET_END_JOIN = 'SET_END_JOIN';
export const CLEAN_JOIN = 'CLEAN_JOIN';
export const SET_EDIT_MODE = 'SET_EDIT_MODE';
